-- House Of Wax V25.43 auth and role access foundation schema for Supabase/Postgres.
-- Run this in the Supabase SQL editor before enabling hosted tester data.
-- Do not place service_role keys in Streamlit client-facing code.

create table if not exists app_users (
    id bigint generated by default as identity primary key,
    auth_user_id uuid unique,
    email text unique,
    display_name text,
    account_type text,
    buyer_id bigint,
    seller_id bigint,
    admin_access text default 'No',
    seller_application_status text default 'Not Applied',
    account_status text default 'Active',
    status text default 'Active',
    local_password_hash text,
    created_at text,
    updated_at text
);

alter table app_users add column if not exists auth_user_id uuid;
alter table app_users add column if not exists email text;
alter table app_users add column if not exists display_name text;
alter table app_users add column if not exists account_type text;
alter table app_users add column if not exists buyer_id bigint;
alter table app_users add column if not exists seller_id bigint;
alter table app_users add column if not exists admin_access text default 'No';
alter table app_users add column if not exists seller_application_status text default 'Not Applied';
alter table app_users add column if not exists account_status text default 'Active';
alter table app_users add column if not exists status text default 'Active';
alter table app_users add column if not exists local_password_hash text;
alter table app_users add column if not exists created_at text;
alter table app_users add column if not exists updated_at text;

create table if not exists buyers (
    id bigint generated by default as identity primary key,
    name text,
    email text unique,
    phone text,
    city text,
    state text,
    bio text,
    avatar_url text,
    status text default 'Trusted Buyer',
    rating numeric default 100,
    completed_purchases integer default 0,
    unpaid_orders integer default 0,
    disputes integer default 0,
    strikes integer default 0,
    created_at text,
    updated_at text
);
alter table buyers add column if not exists avatar_url text;

create table if not exists sellers (
    id bigint generated by default as identity primary key,
    store_name text,
    owner_name text,
    email text unique,
    phone text,
    city text,
    state text,
    website text,
    instagram text,
    store_bio text,
    seller_story text,
    specialties text,
    logo_url text,
    banner_url text,
    status text default 'Approved',
    seller_level text default 'Verified Seller',
    rating numeric default 100,
    completed_sales integer default 0,
    disputes integer default 0,
    strikes integer default 0,
    auction_override text default 'Yes',
    access_code text,
    contact_preference text,
    rules_accepted text default 'No',
    rules_accepted_at text,
    paypal_link text,
    created_at text,
    updated_at text
);

alter table sellers add column if not exists rules_accepted text default 'No';
alter table sellers add column if not exists rules_accepted_at text;
alter table sellers add column if not exists paypal_link text;

create table if not exists products (
    id bigint generated by default as identity primary key,
    seller_id bigint references sellers(id) on delete set null,
    sku text,
    barcode text,
    catalog_number text,
    matrix_runout text,
    category text,
    artist text,
    title text,
    format text,
    label text,
    release_year text,
    genre text,
    media_grade text,
    sleeve_grade text,
    condition_notes text,
    description text,
    price numeric default 0,
    quantity integer default 1,
    shipping_price numeric default 0,
    image_url text,
    reference_image_url text,
    video_url text,
    audio_url text,
    external_release_url text,
    listing_status text default 'Draft',
    listing_type text default 'Fixed Price',
    reviewer_notes text,
    created_at text,
    updated_at text
);

create table if not exists product_gallery (
    id bigint generated by default as identity primary key,
    product_id bigint references products(id) on delete cascade,
    image_url text,
    caption text,
    created_at text
);

create table if not exists listing_inquiries (
    id bigint generated by default as identity primary key,
    product_id bigint references products(id) on delete set null,
    seller_id bigint references sellers(id) on delete set null,
    buyer_id bigint references buyers(id) on delete set null,
    buyer_name text,
    buyer_contact text,
    preferred_contact_method text,
    message text,
    status text default 'New',
    created_at text,
    updated_at text
);

create table if not exists purchase_requests (
    id bigint generated by default as identity primary key,
    product_id bigint references products(id) on delete set null,
    seller_id bigint references sellers(id) on delete set null,
    buyer_id bigint references buyers(id) on delete set null,
    buyer_name text,
    buyer_contact text,
    preferred_contact_method text,
    fulfillment_preference text,
    offer_price numeric default 0,
    buyer_message text,
    status text default 'New',
    counter_price numeric,
    counter_message text,
    payment_due_at text,
    created_at text,
    updated_at text
);
alter table purchase_requests add column if not exists payment_due_at text;

create table if not exists tester_feedback (
    id bigint generated by default as identity primary key,
    tester_name text,
    tester_type text,
    page_flow text,
    worked_well text,
    confusing text,
    felt_broken text,
    missing text,
    ease_rating integer,
    would_use_again text,
    open_notes text,
    status text default 'New',
    created_at text
);

create table if not exists listing_reports (
    id bigint generated by default as identity primary key,
    listing_id bigint,
    seller_id bigint references sellers(id) on delete set null,
    reporter_name text,
    reporter_contact text,
    reason text,
    details text,
    status text default 'Open',
    created_at text,
    updated_at text
);

create table if not exists knowledge_posts (
    id bigint generated by default as identity primary key,
    title text,
    category text,
    audience text,
    level text,
    summary text,
    body text,
    house_tip text,
    image_url text,
    video_url text,
    status text default 'Draft',
    featured text default 'No',
    created_at text,
    updated_at text
);

create table if not exists glossary_terms (
    id bigint generated by default as identity primary key,
    term text unique,
    category text,
    plain_definition text,
    why_it_matters text,
    example text,
    status text default 'Draft',
    created_at text,
    updated_at text
);

-- Homepage Editor content and newsletter signups previously wrote only to
-- local SQLite, which is ephemeral on Streamlit Cloud -- any edits or
-- signups were lost on the next redeploy. These 4 tables move that
-- content (and any real visitor emails) onto persistent storage.
create table if not exists homepage_blocks (
    id bigint generated by default as identity primary key,
    block_name text,
    title text,
    subtitle text,
    body text,
    button_text text,
    button_target text,
    image_url text,
    video_url text,
    status text default 'Active',
    sort_order integer default 0,
    created_at text,
    updated_at text
);

create table if not exists quick_tips (
    id bigint generated by default as identity primary key,
    tip_text text,
    category text,
    status text default 'Active',
    created_at text,
    updated_at text
);

create table if not exists did_you_know (
    id bigint generated by default as identity primary key,
    fact_text text,
    category text,
    status text default 'Active',
    created_at text,
    updated_at text
);

create table if not exists newsletter_signups (
    id bigint generated by default as identity primary key,
    email text,
    name text,
    source text,
    interest text,
    created_at text,
    updated_at text
);

-- Seller engagement features below had the same local-only problem as
-- the homepage content above: followers, store policies, announcements,
-- events, and badges all reset on every Streamlit Cloud redeploy.
create table if not exists seller_followers (
    id bigint generated by default as identity primary key,
    seller_id integer,
    buyer_id integer,
    created_at text
);

create table if not exists seller_badges (
    id bigint generated by default as identity primary key,
    seller_id integer,
    badge_name text,
    badge_type text,
    active text default 'Yes',
    created_at text
);

create table if not exists store_announcements (
    id bigint generated by default as identity primary key,
    seller_id integer,
    title text,
    body text,
    status text default 'Active',
    created_at text
);

create table if not exists seller_events (
    id bigint generated by default as identity primary key,
    seller_id integer,
    event_title text,
    event_type text,
    event_date text,
    description text,
    status text default 'Active',
    created_at text
);

create table if not exists seller_policies (
    seller_id integer primary key,
    shipping_policy text,
    return_policy text,
    grading_policy text,
    customer_service_policy text,
    buyer_requirements text,
    local_pickup_policy text,
    processing_time text
);

-- want_list, seller_reviews, and avatar_faq_videos are in app.py's
-- CORE_HOSTED_TABLES and have been live features for a while, but were
-- never added to this file -- found during the V25.43 RLS/grants audit.
-- Whatever their actual live structure turned out to be, these three
-- statement blocks (create + add-column-if-not-exists) are safe to run
-- against an already-existing table: they only add what's missing, never
-- drop or alter existing data.
create table if not exists want_list (
    id bigint generated by default as identity primary key,
    buyer_id bigint,
    artist text,
    title text,
    status text default 'Active',
    created_at text,
    updated_at text
);
alter table want_list add column if not exists buyer_id bigint;
alter table want_list add column if not exists artist text;
alter table want_list add column if not exists title text;
alter table want_list add column if not exists status text default 'Active';
alter table want_list add column if not exists created_at text;
alter table want_list add column if not exists updated_at text;

create table if not exists seller_reviews (
    id bigint generated by default as identity primary key,
    seller_id bigint,
    buyer_id bigint,
    purchase_request_id bigint,
    product_id bigint,
    rating integer,
    review_text text,
    buyer_display_name text,
    created_at text,
    updated_at text
);
alter table seller_reviews add column if not exists seller_id bigint;
alter table seller_reviews add column if not exists buyer_id bigint;
alter table seller_reviews add column if not exists purchase_request_id bigint;
alter table seller_reviews add column if not exists product_id bigint;
alter table seller_reviews add column if not exists rating integer;
alter table seller_reviews add column if not exists review_text text;
alter table seller_reviews add column if not exists buyer_display_name text;
alter table seller_reviews add column if not exists created_at text;
alter table seller_reviews add column if not exists updated_at text;

create table if not exists avatar_faq_videos (
    id bigint generated by default as identity primary key,
    question text,
    video_url text,
    display_order integer default 0,
    status text default 'Active',
    created_at text,
    updated_at text
);
alter table avatar_faq_videos add column if not exists question text;
alter table avatar_faq_videos add column if not exists video_url text;
alter table avatar_faq_videos add column if not exists display_order integer default 0;
alter table avatar_faq_videos add column if not exists status text default 'Active';
alter table avatar_faq_videos add column if not exists created_at text;
alter table avatar_faq_videos add column if not exists updated_at text;

-- culture_posts backs the admin "Seller Spotlight" tool (Community tools ->
-- Create seller spotlight culture post). It existed in app.py long before
-- this file was written but was never added here, and had no seller_id
-- column -- found during the same audit that caught want_list/seller_reviews/
-- avatar_faq_videos. Without seller_id there was no way to show a spotlight
-- post on the seller's own store page, so it's added here from the start.
create table if not exists culture_posts (
    id bigint generated by default as identity primary key,
    seller_id bigint references sellers(id) on delete set null,
    title text,
    category text,
    author text,
    body text,
    image_url text,
    status text default 'Published',
    created_at text
);
alter table culture_posts add column if not exists seller_id bigint;
alter table culture_posts add column if not exists title text;
alter table culture_posts add column if not exists category text;
alter table culture_posts add column if not exists author text;
alter table culture_posts add column if not exists body text;
alter table culture_posts add column if not exists image_url text;
alter table culture_posts add column if not exists status text default 'Published';
alter table culture_posts add column if not exists created_at text;

-- cart_items: a buyer's pre-checkout cart. One row per (buyer, listing) --
-- every listing here is a unique physical copy, not a restockable SKU, so
-- there is deliberately no quantity column (Buy Now already reserves the
-- whole listing, and products.quantity is never decremented anywhere in the
-- purchase flow). seller_id/added_price are denormalized off products the
-- same way purchase_requests already denormalizes seller_id -- avoids a
-- join at cart-grouping time. added_price is display-only ("added at $X");
-- checkout always re-reads the live products.price, never this column.
create table if not exists cart_items (
    id bigint generated by default as identity primary key,
    buyer_id bigint references buyers(id) on delete cascade,
    product_id bigint references products(id) on delete cascade,
    seller_id bigint references sellers(id) on delete set null,
    added_price numeric default 0,
    created_at text,
    updated_at text
);
alter table cart_items add column if not exists buyer_id bigint;
alter table cart_items add column if not exists product_id bigint;
alter table cart_items add column if not exists seller_id bigint;
alter table cart_items add column if not exists added_price numeric default 0;
alter table cart_items add column if not exists created_at text;
alter table cart_items add column if not exists updated_at text;

alter table app_users enable row level security;
alter table buyers enable row level security;
alter table sellers enable row level security;
alter table products enable row level security;
alter table product_gallery enable row level security;
alter table listing_inquiries enable row level security;
alter table purchase_requests enable row level security;
alter table tester_feedback enable row level security;
alter table listing_reports enable row level security;
alter table knowledge_posts enable row level security;
alter table glossary_terms enable row level security;
alter table homepage_blocks enable row level security;
alter table quick_tips enable row level security;
alter table did_you_know enable row level security;
alter table newsletter_signups enable row level security;
alter table seller_followers enable row level security;
alter table seller_badges enable row level security;
alter table store_announcements enable row level security;
alter table seller_events enable row level security;
alter table seller_policies enable row level security;
alter table want_list enable row level security;
alter table seller_reviews enable row level security;
alter table avatar_faq_videos enable row level security;
alter table culture_posts enable row level security;
alter table cart_items enable row level security;

-- Apply V25.43 ownership policies from supabase_core_policies.sql after creating tables.
