-- House Of Wax V25.37 core persistence schema for Supabase/Postgres.
-- Run this in the Supabase SQL editor before enabling hosted tester data.
-- Prototype-friendly policies are included for anon-key testing. Tighten RLS before production.

create table if not exists buyers (
    id bigint generated by default as identity primary key,
    name text,
    email text unique,
    phone text,
    city text,
    state text,
    bio text,
    status text default 'Trusted Buyer',
    rating numeric default 100,
    completed_purchases integer default 0,
    unpaid_orders integer default 0,
    disputes integer default 0,
    strikes integer default 0,
    created_at text,
    updated_at text
);

create table if not exists sellers (
    id bigint generated by default as identity primary key,
    store_name text,
    owner_name text,
    email text unique,
    phone text,
    city text,
    state text,
    website text,
    instagram text,
    store_bio text,
    seller_story text,
    specialties text,
    logo_url text,
    banner_url text,
    status text default 'Approved',
    seller_level text default 'Verified Seller',
    rating numeric default 100,
    completed_sales integer default 0,
    disputes integer default 0,
    strikes integer default 0,
    auction_override text default 'Yes',
    access_code text,
    contact_preference text,
    created_at text,
    updated_at text
);

create table if not exists products (
    id bigint generated by default as identity primary key,
    seller_id bigint references sellers(id) on delete set null,
    sku text,
    barcode text,
    catalog_number text,
    matrix_runout text,
    category text,
    artist text,
    title text,
    format text,
    label text,
    release_year text,
    genre text,
    media_grade text,
    sleeve_grade text,
    condition_notes text,
    description text,
    price numeric default 0,
    quantity integer default 1,
    shipping_price numeric default 0,
    image_url text,
    video_url text,
    audio_url text,
    external_release_url text,
    listing_status text default 'Draft',
    listing_type text default 'Fixed Price',
    reviewer_notes text,
    created_at text,
    updated_at text
);

create table if not exists product_gallery (
    id bigint generated by default as identity primary key,
    product_id bigint references products(id) on delete cascade,
    image_url text,
    caption text,
    created_at text
);

create table if not exists listing_inquiries (
    id bigint generated by default as identity primary key,
    product_id bigint references products(id) on delete set null,
    seller_id bigint references sellers(id) on delete set null,
    buyer_id bigint references buyers(id) on delete set null,
    buyer_name text,
    buyer_contact text,
    preferred_contact_method text,
    message text,
    status text default 'New',
    created_at text,
    updated_at text
);

create table if not exists purchase_requests (
    id bigint generated by default as identity primary key,
    product_id bigint references products(id) on delete set null,
    seller_id bigint references sellers(id) on delete set null,
    buyer_id bigint references buyers(id) on delete set null,
    buyer_name text,
    buyer_contact text,
    preferred_contact_method text,
    fulfillment_preference text,
    offer_price numeric default 0,
    buyer_message text,
    status text default 'New',
    created_at text,
    updated_at text
);

create table if not exists tester_feedback (
    id bigint generated by default as identity primary key,
    tester_name text,
    tester_type text,
    page_flow text,
    worked_well text,
    confusing text,
    felt_broken text,
    missing text,
    ease_rating integer,
    would_use_again text,
    open_notes text,
    status text default 'New',
    created_at text
);

alter table buyers enable row level security;
alter table sellers enable row level security;
alter table products enable row level security;
alter table product_gallery enable row level security;
alter table listing_inquiries enable row level security;
alter table purchase_requests enable row level security;
alter table tester_feedback enable row level security;

do $$
declare
    t text;
begin
    foreach t in array array['buyers','sellers','products','product_gallery','listing_inquiries','purchase_requests','tester_feedback']
    loop
        execute format('drop policy if exists "prototype anon read %s" on %I', t, t);
        execute format('drop policy if exists "prototype anon insert %s" on %I', t, t);
        execute format('drop policy if exists "prototype anon update %s" on %I', t, t);
        execute format('create policy "prototype anon read %s" on %I for select to anon using (true)', t, t);
        execute format('create policy "prototype anon insert %s" on %I for insert to anon with check (true)', t, t);
        execute format('create policy "prototype anon update %s" on %I for update to anon using (true) with check (true)', t, t);
    end loop;
end $$;
