-- House Of Wax V25.43 auth and role access foundation schema for Supabase/Postgres.
-- Run this in the Supabase SQL editor before enabling hosted tester data.
-- Do not place service_role keys in Streamlit client-facing code.

create table if not exists app_users (
    id bigint generated by default as identity primary key,
    auth_user_id uuid unique,
    email text unique,
    display_name text,
    account_type text,
    buyer_id bigint,
    seller_id bigint,
    admin_access text default 'No',
    status text default 'Active',
    local_password_hash text,
    created_at text,
    updated_at text
);

alter table app_users add column if not exists auth_user_id uuid;
alter table app_users add column if not exists email text;
alter table app_users add column if not exists display_name text;
alter table app_users add column if not exists account_type text;
alter table app_users add column if not exists buyer_id bigint;
alter table app_users add column if not exists seller_id bigint;
alter table app_users add column if not exists admin_access text default 'No';
alter table app_users add column if not exists status text default 'Active';
alter table app_users add column if not exists local_password_hash text;
alter table app_users add column if not exists created_at text;
alter table app_users add column if not exists updated_at text;

create table if not exists buyers (
    id bigint generated by default as identity primary key,
    name text,
    email text unique,
    phone text,
    city text,
    state text,
    bio text,
    status text default 'Trusted Buyer',
    rating numeric default 100,
    completed_purchases integer default 0,
    unpaid_orders integer default 0,
    disputes integer default 0,
    strikes integer default 0,
    created_at text,
    updated_at text
);

create table if not exists sellers (
    id bigint generated by default as identity primary key,
    store_name text,
    owner_name text,
    email text unique,
    phone text,
    city text,
    state text,
    website text,
    instagram text,
    store_bio text,
    seller_story text,
    specialties text,
    logo_url text,
    banner_url text,
    status text default 'Approved',
    seller_level text default 'Verified Seller',
    rating numeric default 100,
    completed_sales integer default 0,
    disputes integer default 0,
    strikes integer default 0,
    auction_override text default 'Yes',
    access_code text,
    contact_preference text,
    rules_accepted text default 'No',
    rules_accepted_at text,
    created_at text,
    updated_at text
);

alter table sellers add column if not exists rules_accepted text default 'No';
alter table sellers add column if not exists rules_accepted_at text;

create table if not exists products (
    id bigint generated by default as identity primary key,
    seller_id bigint references sellers(id) on delete set null,
    sku text,
    barcode text,
    catalog_number text,
    matrix_runout text,
    category text,
    artist text,
    title text,
    format text,
    label text,
    release_year text,
    genre text,
    media_grade text,
    sleeve_grade text,
    condition_notes text,
    description text,
    price numeric default 0,
    quantity integer default 1,
    shipping_price numeric default 0,
    image_url text,
    video_url text,
    audio_url text,
    external_release_url text,
    listing_status text default 'Draft',
    listing_type text default 'Fixed Price',
    reviewer_notes text,
    created_at text,
    updated_at text
);

create table if not exists product_gallery (
    id bigint generated by default as identity primary key,
    product_id bigint references products(id) on delete cascade,
    image_url text,
    caption text,
    created_at text
);

create table if not exists listing_inquiries (
    id bigint generated by default as identity primary key,
    product_id bigint references products(id) on delete set null,
    seller_id bigint references sellers(id) on delete set null,
    buyer_id bigint references buyers(id) on delete set null,
    buyer_name text,
    buyer_contact text,
    preferred_contact_method text,
    message text,
    status text default 'New',
    created_at text,
    updated_at text
);

create table if not exists purchase_requests (
    id bigint generated by default as identity primary key,
    product_id bigint references products(id) on delete set null,
    seller_id bigint references sellers(id) on delete set null,
    buyer_id bigint references buyers(id) on delete set null,
    buyer_name text,
    buyer_contact text,
    preferred_contact_method text,
    fulfillment_preference text,
    offer_price numeric default 0,
    buyer_message text,
    status text default 'New',
    created_at text,
    updated_at text
);

create table if not exists tester_feedback (
    id bigint generated by default as identity primary key,
    tester_name text,
    tester_type text,
    page_flow text,
    worked_well text,
    confusing text,
    felt_broken text,
    missing text,
    ease_rating integer,
    would_use_again text,
    open_notes text,
    status text default 'New',
    created_at text
);

create table if not exists listing_reports (
    id bigint generated by default as identity primary key,
    listing_id bigint,
    seller_id bigint references sellers(id) on delete set null,
    reporter_name text,
    reporter_contact text,
    reason text,
    details text,
    status text default 'Open',
    created_at text,
    updated_at text
);

create table if not exists knowledge_posts (
    id bigint generated by default as identity primary key,
    title text,
    category text,
    audience text,
    level text,
    summary text,
    body text,
    house_tip text,
    image_url text,
    video_url text,
    status text default 'Draft',
    featured text default 'No',
    created_at text,
    updated_at text
);

create table if not exists glossary_terms (
    id bigint generated by default as identity primary key,
    term text unique,
    category text,
    plain_definition text,
    why_it_matters text,
    example text,
    status text default 'Draft',
    created_at text,
    updated_at text
);

alter table app_users enable row level security;
alter table buyers enable row level security;
alter table sellers enable row level security;
alter table products enable row level security;
alter table product_gallery enable row level security;
alter table listing_inquiries enable row level security;
alter table purchase_requests enable row level security;
alter table tester_feedback enable row level security;
alter table listing_reports enable row level security;
alter table knowledge_posts enable row level security;
alter table glossary_terms enable row level security;

-- Apply V25.43 ownership policies from supabase_core_policies.sql after creating tables.
